### ISSUE TITLE
Doesn't apply the UILabel's shadow properties

### ISSUE THREAD

**Issue by badeen** [LemonCake/MSLabel#5]
The drawing ignores any shadow settings applied to the UILabel. This can easily be fixed by inserting the following after line 33 in MSLabel.m:

CGContextSetShadowWithColor(UIGraphicsGetCurrentContext(), self.shadowOffset, 0, self.shadowColor.CGColor);

**Comment by mporeh** [comment]
in the initFrame? doesnt sound right.... CG methods calls are done only in drawRect/drawTextInRect
i would love to get the correct answer to this since i am trying to imlement shadow and gradient effect with no success
(i am trying to combine your label with this guy's label here http://blog.athenstean.com/post/22047566786/stylish-uitextfield-uilabel-with-gradients-and-drop)

**Comment by youens** [comment]
Adding it just before drawAtPoint: in drawRect did the trick for me.  Thanks @badeen!

**Comment by LemonCake** [comment]
Added this. Thanks for pointing it out.
